### ISSUE TITLE
Glossary - Trivial update - Description of EDL

### ISSUE THREAD

**Issue by glennl** [oresat/uniclogs-software#39]
EDL
Engineering Data Link.
A bi-directional data link between the UniClOGS ground station and the OreSat spacecraft. Specifically it's UpLink is sent by UniClOGS on L band and received by OreSat, and it's DownLink is sent by OreSat on UHF and received by UniClOGS. It can contain critical engineering data, software updates for OreSat’s subsystems, or files from OreSat’s subsystems.

**Comment by dmitri-mcguckin** [comment]
Closed with 3ce7fa86feefb4c8ce5bc75dd1f5160a90dd7061.
