### ISSUE TITLE
Glossary - Trivial Update - UHF and L band

### ISSUE THREAD

**Issue by glennl** [oresat/uniclogs-software#40]
UHF
Ultra High Frequency. The range of radio frequencies from 300 MHz to 1 GHz.

L band
Microwave band above UHF. The range of radio frequencies from 1GHz to 2 GHz.

**Comment by dmitri-mcguckin** [comment]
Closed with 3ce7fa86feefb4c8ce5bc75dd1f5160a90dd7061.
